schema_version = "1.0.0"

id = "airfoe_blender_tooling"
version = "1.0.0"
name = "Airfoe Blender Tooling"
tagline = "Internal Airfoe Tools"
maintainer = "fynn.luft@airfoe.com"
type = "add-on"

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

[permissions]
# network = "Needs to send simple http post requests to localhost:5000"

[build]
paths_exclude_pattern = [
  "builds/*",
  ".git/*",
  ".github/*",
  "__pycache__/*",
  "*.pyc",
  "*.blend1",
  "*.tar.xz",
  "*.zip",
]
