# AUTO-GENERATED FILE

from .preferences import Airfoe_Preferences
from .ValidatorPropertyGroup import USD_PG_ExportHookSettings
from .operators.FILE_OT_MakeAsset import FILE_OT_MakeAsset
from .operators.FILE_OT_OpenAsset import FILE_OT_OpenAsset
from .operators.FILE_OT_SetAssetType import FILE_OT_SetAssetType
from .operators.OBJECT_OT_ExportFBX import OBJECT_OT_ExportFBX
from .operators.OBJECT_OT_ExportUSD import OBJECT_OT_ExportUSD
from .operators.OBJECT_OT_FixValidationIssue import OBJECT_OT_FixValidationIssue
from .operators.OBJECT_OT_Group import OBJECT_OT_Group
from .operators.OBJECT_OT_MakeCollider import OBJECT_OT_MakeCollider
from .operators.OBJECT_OT_MakeQuickCollision import OBJECT_OT_MakeQuickCollision
from .operators.OBJECT_OT_MarkAsPurpose import OBJECT_OT_MarkAsPurpose
from .operators.OBJECT_OT_SelectObject import OBJECT_OT_SelectObject
from .operators.OBJECT_OT_ShowColliders import OBJECT_OT_ShowColliders
from .operators.OBJECT_OT_ValidateUSD import OBJECT_OT_ValidateUSD
from .operators.USD_OT_USDHook import USD_OT_USDHook
from .panels.VIEW3D_PT_UI_Sample import VIEW3D_PT_UI_Sample
from .panels.VIEW_3D_PT_Material import VIEW3D_PT_UI_Material
from .panels.VIEW_3D_PT_SceneTools import VIEW3D_PT_SceneTools
from .scene_validation.PropertyGroups import USD_PG_ValidationIssue
from .scene_validation.PropertyGroups import USD_PG_ValidatorCache
from .scene_validation.PropertyGroups import USD_PG_ValidatorSettings

CLASSES = (

#preferences
Airfoe_Preferences,

#Property Groups
USD_PG_ExportHookSettings,
USD_PG_ValidationIssue,
USD_PG_ValidatorCache,
USD_PG_ValidatorSettings,

#Operators
FILE_OT_MakeAsset,
FILE_OT_OpenAsset,
FILE_OT_SetAssetType,
OBJECT_OT_ExportFBX,
OBJECT_OT_ExportUSD,
OBJECT_OT_FixValidationIssue,
OBJECT_OT_Group,
OBJECT_OT_MakeCollider,
OBJECT_OT_MakeQuickCollision,
OBJECT_OT_MarkAsPurpose,
OBJECT_OT_SelectObject,
OBJECT_OT_ShowColliders,
OBJECT_OT_ValidateUSD,
USD_OT_USDHook,

#Panels
VIEW3D_PT_UI_Sample,
VIEW3D_PT_UI_Material,
VIEW3D_PT_SceneTools,
)
